### ISSUE TITLE
Ultima subfigura vacía en visualización exploracion español

### ISSUE THREAD

**Issue by camilocarvajalreyes** [furrutiav/data-mining-2022#7]
Como "falta" un emoji en español la última subfigura de la grilla de 4x5 quedó vacía. Esto genera un objeto matplotlib en blanco que tapa parcialmente una de las visualizaciones. Esto sucede tanto en el .ipynb como en el posterior html

**Comment by furrutiav** [comment]
resuelto! Agregue la siguiente linea:
`
k = len(set(df_es_mapping["label"]))
axk = ax[k//5, k%5]
axk.remove()
`
Actualizado en el ultimo commit.
